services:
  email_service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: email_service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/email_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: email_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d email_service" ]
      interval: 5s
      timeout: 5s
      retries: 5